export class Oglas{
    Name:string
    City:string
    Municipality:string
    Microlocation:string
    Street:string   
    Area:number
    Rooms:number
    ConstructionYear:number
    State:string
    Heating:string
    Floor:number
    TotalFloors:number
    Parking:string
    MonthlyUtilities:string
    Price:number
    About:string
    Characteristics:Array<string>
    images:Array<string>
    Advertiser:Array<object>
    sold:boolean
}